# Generated by Django 2.1 on 2018-09-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=254)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.Patient')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.Trial')),
            ],
        ),
    ]
