# Generated by Django 2.1 on 2018-09-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0002_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='name',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='patient',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='patient_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='trial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trialapp.Trial'),
        ),
    ]
