# Generated by Django 2.1 on 2018-09-27 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0003_auto_20180925_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrialList',
        ),
        migrations.AlterField(
            model_name='trial',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
