# Generated by Django 2.1 on 2018-09-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0004_auto_20180926_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigator',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='investigator',
            table=None,
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
        migrations.AlterModelTable(
            name='operator',
            table=None,
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
        migrations.AlterModelTable(
            name='trial',
            table=None,
        ),
    ]
