# Generated by Django 2.1 on 2018-10-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0004_auto_20181015_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('c', 'cat'), ('r', 'rabbit'), ('d', 'dog')], max_length=1)),
            ],
        ),
    ]
