# Generated by Django 2.1 on 2018-10-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0005_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
